export const properties = [
  {
    slug: "muckle-view",
    name: "Muckle View",
    lodgifyRentalId: "646178",
    // Listed nightly rate range from Lodgify (original_min/max_price, not
    // the guest-facing price with booking-engine markup) — a rough band
    // for schema.org priceRange, checked 2026-08-29. Update if rates shift
    // materially.
    priceRange: "£165–£295",
    sleeps: 2,
    description:
      "A contemporary studio chalet perched on the clifftop, with panoramic views across the Moray Firth and a log burner for cosy evenings in.",
    tagline: "For Couples and Their Dog",
    longDescription: [
      "Designed for two and genuinely built with dogs in mind, each studio chalet is design-led, beautifully finished, and shaped entirely around the view. Scottish and Scandinavian furnishings bring warm textures and natural materials into every corner, with pieces sourced from small local makers. The log burner keeps evenings cosy, while the balcony binoculars are there for dolphins, the aurora, and everything in between.",
      "These are dog-friendly chalets in Aberdeenshire where your companion is every bit as welcome as you are.",
    ],
    features: [
      "Sleeps 2",
      "Dog-friendly throughout",
      "Kitchen with coffee machine, grill, stove, microwave, oven, refrigerator, toaster",
      "Luxury bathroom with power shower & Gordon Castle toiletries",
      "Clifftop sea views over the Moray Firth",
      "Private balcony with binoculars",
      "Log burner",
      "On-site EV charging",
      "Wheelchair accessible",
    ],
    comingSoon: false,
    location: { lat: 57.670563223386880, lng: -2.337134626983644 },
    image: {
      src: "/7907_Gamrie_High_158.jpg",
      width: 7871,
      height: 5249,
      alt: "Muckle View studio chalet on the clifftop above Gardenstown with Moray Firth views.",
    },
    gallery: [
      { src: "/Muckle View/1.jpg", width: 1920, height: 1280, alt: "Muckle View chalet above the shore, beside the old boat sheds" },
      { src: "/Muckle View/2.jpg", width: 1920, height: 1281, alt: "Muckle View on the hillside beside Gardenstown Public Hall" },
      { src: "/Muckle View/3.jpg", width: 1920, height: 1280, alt: "Glazed gable end and terrace looking out to the Moray Firth" },
      { src: "/Muckle View/4.jpg", width: 1920, height: 1280, alt: "Clifftop terrace seating with a lantern at dusk" },
      { src: "/Muckle View/5.jpg", width: 1920, height: 1280, alt: "\"Muckle View\" nameplate on the timber cladding" },
      { src: "/Muckle View/6.jpg", width: 1920, height: 1281, alt: "Electric car charging by the front door, with the bay beyond" },
      { src: "/Muckle View/7.jpg", width: 1920, height: 1281, alt: "Front door with EV charge point and entry keypad" },
      { src: "/Muckle View/8.jpg", width: 1920, height: 1281, alt: "Muckle View glowing at dusk with the gable window lit" },
      { src: "/Muckle View/9.jpg", width: 1920, height: 1280, alt: "Twilight view across the terrace seating to the sea" },
      { src: "/Muckle View/10.jpg", width: 1920, height: 1280, alt: "Sunset from the balcony with coloured accent lighting" },
      { src: "/Muckle View/11.jpg", width: 1920, height: 1280, alt: "The Northern Lights over Gardenstown, seen from Muckle View" },
      { src: "/Muckle View/12.jpg", width: 1920, height: 1280, alt: "Sunset silhouette over the Aberdeenshire coast" },
      { src: "/Muckle View/13.jpg", width: 1920, height: 1280, alt: "Gardenstown village and bay framed through the window" },
      { src: "/Muckle View/14.jpg", width: 1920, height: 1281, alt: "Watching the coast through binoculars with the resident dog" },
      { src: "/Muckle View/15.jpg", width: 1920, height: 1281, alt: "Waves breaking over the rocks below the chalet" },
      { src: "/Muckle View/16.jpg", width: 1920, height: 1280, alt: "Fishing boats moored in Gardenstown Harbour" },
      { src: "/Muckle View/17.jpg", width: 1920, height: 1280, alt: "Gardenstown village tucked beneath the cliffs" },
      { src: "/Muckle View/18.jpg", width: 1920, height: 1280, alt: "Colourful cottages along the shoreline near Gardenstown" },
      { src: "/Muckle View/19.jpg", width: 1668, height: 2500, alt: "Gamrie Chalets gin and tonic on the terrace table" },
      { src: "/Muckle View/20.jpg", width: 1920, height: 1281, alt: "Gin and tonic with a wood-panelled backdrop" },
      { src: "/Muckle View/21.jpg", width: 1667, height: 2500, alt: "White wine on the terrace overlooking the cliffs" },
      { src: "/Muckle View/22.jpg", width: 1920, height: 1281, alt: "Twilight sea view through the vaulted gable window" },
      { src: "/Muckle View/23.jpg", width: 1920, height: 1280, alt: "Bedroom with vaulted ceiling and sea-view windows" },
      { src: "/Muckle View/24.jpg", width: 1920, height: 1280, alt: "Bedroom with round mirror, wall-mounted TV, and log burner" },
      { src: "/Muckle View/25.jpg", width: 1920, height: 1281, alt: "Armchair with a tartan throw and binoculars on the shelf" },
      { src: "/Muckle View/26.jpg", width: 1920, height: 1280, alt: "Bed with cushions and a desk nook beyond" },
      { src: "/Muckle View/27.jpg", width: 1920, height: 1280, alt: "The resident dog resting on a sheepskin rug by the door" },
      { src: "/Muckle View/28.jpg", width: 1920, height: 1281, alt: "Round mirror reflecting the vaulted ceiling and flue" },
      { src: "/Muckle View/29.jpg", width: 1920, height: 1280, alt: "Close-up of the studio's statement pendant light" },
      { src: "/Muckle View/30.jpg", width: 1920, height: 1281, alt: "Floating bedside table beneath a pendant light" },
      { src: "/Muckle View/31.jpg", width: 1920, height: 1280, alt: "Bedside table with a book and a glass of water" },
      { src: "/Muckle View/32.jpg", width: 1920, height: 1281, alt: "Breakfast tray with yoghurt, fruit, coffee, and orange juice" },
      { src: "/Muckle View/33.jpg", width: 1920, height: 1281, alt: "Wall-mounted TV streaming Netflix above a small desk" },
      { src: "/Muckle View/34.jpg", width: 1668, height: 2500, alt: "Desk nook beside the log burner flue and open bi-fold doors" },
      { src: "/Muckle View/35.jpg", width: 1920, height: 1281, alt: "Log burner lit beside a reading chair with a book" },
      { src: "/Muckle View/36.jpg", width: 1920, height: 1280, alt: "Croissant and coffee on the tray table" },
      { src: "/Muckle View/37.jpg", width: 1667, height: 2500, alt: "The resident dog asleep in a patch of sunlight" },
      { src: "/Muckle View/38.jpg", width: 1920, height: 1281, alt: "Navy kitchen with oven, hob, and sea-view splashback" },
      { src: "/Muckle View/39.jpg", width: 1668, height: 2500, alt: "Kitchen counter detail with fresh bread and kettle" },
      { src: "/Muckle View/40.jpg", width: 1920, height: 1280, alt: "Espresso machine with a selection of coffee pods" },
      { src: "/Muckle View/41.jpg", width: 1920, height: 1281, alt: "Marble bathroom with walk-in shower and vanity" },
      { src: "/Muckle View/42.jpg", width: 1920, height: 1281, alt: "Bathroom sink detail with Gordon Castle toiletries" },
      { src: "/Muckle View/43.jpg", width: 1920, height: 1280, alt: "Branded bathrobes reflected in the bathroom mirror" },
    ],
  },
  {
    slug: "murray-cottage",
    name: "Murray Cottage",
    lodgifyRentalId: "794951",
    priceRange: "£104–£262",
    sleeps: 6,
    description:
      "The family home above Gardenstown, with three bedrooms, sweeping views of the Moray Firth, and room for everyone to settle in.",
    tagline: "Space for Everyone",
    longDescription: [
      "More generous in scale, the family home gives you room to spread out and truly settle in without losing an ounce of the stunning setting. The same considered design runs throughout: quality furnishings, local touches, and that sweeping view of the Firth framed in every window. It's the kind of place where children remember the holiday for years, and parents finally, properly rest.",
    ],
    features: [
      "Ideal for families and larger groups – 3 bedrooms (4 beds) – Sleeps 6",
      "Dog-friendly throughout",
      "Sea views over the Moray Firth",
      "Log burner",
      "Kitchen with coffee machine, dishwasher, washing machine, stove, microwave, oven, refrigerator, toaster, vacuum cleaner",
      "Luxury bathroom with power shower",
      "Wi-fi",
    ],
    comingSoon: false,
    location: { lat: 57.671059600000000, lng: -2.333991600000000 },
    image: {
      src: "/78491_Murray-002.jpg",
      width: 4999,
      height: 3333,
      alt: "Murray Cottage family home above Gardenstown with sea views.",
    },
    gallery: [
      { src: "/Murray Cottage/1.jpg", width: 1920, height: 1280, alt: "Coastal view from the lounge chairs at Murray Cottage" },
      { src: "/Murray Cottage/2.jpg", width: 1920, height: 1280, alt: "Murray Cottage exterior on the terraced street" },
      { src: "/Murray Cottage/3.jpg", width: 1920, height: 1280, alt: "The Murray Cottage nameplate" },
      { src: "/Murray Cottage/4.jpg", width: 1920, height: 1280, alt: "Rear exterior with solar panels and a paved patio" },
      { src: "/Murray Cottage/5.jpg", width: 1920, height: 1280, alt: "Headland view with seabirds overhead" },
      { src: "/Murray Cottage/6.jpg", width: 1920, height: 1280, alt: "The rugged coastline near Gardenstown" },
      { src: "/Murray Cottage/7.jpg", width: 1920, height: 1280, alt: "A fishing boat working the bay" },
      { src: "/Murray Cottage/8.jpg", width: 1920, height: 1280, alt: "Colourful cottages along the shoreline near Gardenstown" },
      { src: "/Murray Cottage/9.jpg", width: 1920, height: 1280, alt: "Fishing boats in Gardenstown Harbour" },
      { src: "/Murray Cottage/10.jpg", width: 1920, height: 1280, alt: "Sunset over the headland" },
      { src: "/Murray Cottage/11.jpg", width: 1920, height: 1280, alt: "The Northern Lights over Gardenstown" },
      { src: "/Murray Cottage/12.jpg", width: 1920, height: 2880, alt: "Reading corner by the log burner" },
      { src: "/Murray Cottage/13.jpg", width: 1920, height: 1280, alt: "Dining table at Murray Cottage" },
      { src: "/Murray Cottage/14.jpg", width: 1920, height: 1280, alt: "Kitchen worktop with oven, hob, and coffee machine" },
      { src: "/Murray Cottage/15.jpg", width: 1920, height: 2880, alt: "Staircase with a patterned stair runner" },
      { src: "/Murray Cottage/16.jpg", width: 1920, height: 1280, alt: "Porthole mirror in the upstairs hallway" },
      { src: "/Murray Cottage/17.jpg", width: 1920, height: 1284, alt: "Sea view through the twin windows" },
      { src: "/Murray Cottage/18.jpg", width: 1920, height: 2884, alt: "Model sailboat on the windowsill, sea beyond" },
      { src: "/Murray Cottage/19.jpg", width: 1920, height: 1280, alt: "Tiered garden patio with steps" },
      { src: "/Murray Cottage/20.jpg", width: 1920, height: 1280, alt: "Living room at Murray Cottage" },
      { src: "/Murray Cottage/21.jpg", width: 1920, height: 1280, alt: "Living room with the antique grandfather clock" },
      { src: "/Murray Cottage/22.jpg", width: 1920, height: 1280, alt: "Kitchen and dining area" },
      { src: "/Murray Cottage/23.jpg", width: 1920, height: 1280, alt: "Kitchen at Murray Cottage" },
      { src: "/Murray Cottage/24.jpg", width: 1920, height: 1280, alt: "Hallway with a sea view beyond" },
      { src: "/Murray Cottage/25.jpg", width: 1920, height: 1280, alt: "Bathroom with walk-in shower and marble tile" },
      { src: "/Murray Cottage/26.jpg", width: 1920, height: 1280, alt: "Bathroom sink and heated towel rail" },
      { src: "/Murray Cottage/27.jpg", width: 1920, height: 1280, alt: "Shower control panel detail" },
      { src: "/Murray Cottage/28.jpg", width: 1920, height: 1280, alt: "Upstairs landing with a sliding barn door" },
      { src: "/Murray Cottage/29.jpg", width: 1920, height: 1280, alt: "Staircase down towards the bathroom" },
      { src: "/Murray Cottage/30.jpg", width: 1920, height: 1280, alt: "Bedroom with a clifftop view" },
      { src: "/Murray Cottage/31.jpg", width: 1920, height: 1280, alt: "Bedroom with driftwood-base lamps" },
      { src: "/Murray Cottage/32.jpg", width: 1920, height: 1280, alt: "Bedroom with a rattan headboard and fitted wardrobes" },
      { src: "/Murray Cottage/33.jpg", width: 1920, height: 1280, alt: "Twin bedroom with garden views" },
      { src: "/Murray Cottage/34.jpg", width: 1920, height: 1280, alt: "Twin beds with a tartan blanket" },
    ],
  },
  {
    slug: "mohr-rest",
    name: "Mohr Rest",
    sleeps: 2,
    description:
      "A new chalet joining Gamrie Chalets, currently being prepared. Details and availability coming soon.",
    tagline: "For Couples and Their Dog",
    longDescription: [
      "Designed for two and genuinely built with dogs in mind, each studio chalet is design-led, beautifully finished, and shaped entirely around the view. Scottish and Scandinavian furnishings bring warm textures and natural materials into every corner, with pieces sourced from small local makers. The log burner keeps evenings cosy, while the balcony binoculars are there for dolphins, the aurora, and everything in between.",
      "These are dog-friendly chalets in Aberdeenshire where your companion is every bit as welcome as you are.",
    ],
    features: [
      "Sleeps 2",
      "Dog-friendly throughout",
      "Kitchen with coffee machine, grill, stove, microwave, oven, refrigerator, toaster",
      "Luxury bathroom with power shower & Gordon Castle toiletries",
      "Clifftop sea views over the Moray Firth",
      "Private balcony with binoculars",
      "Log burner",
      "On-site EV charging",
      "Wheelchair accessible",
    ],
    comingSoon: true,
    location: { lat: 57.670563223386880, lng: -2.337134626983644 },
    image: {
      src: "/Mohr Rest - Coming Soon.jpeg",
      width: 1920,
      height: 1440,
      alt: "Mohr Rest, a new chalet joining Gamrie Chalets above Gardenstown, coming soon.",
    },
  },
];

export const bookableProperties = properties.filter((p) => !p.comingSoon);
