export const properties = [
  {
    slug: "muckle-view",
    name: "Muckle View",
    lodgifyRentalId: "646178",
    // Listed nightly rate range from Lodgify (original_min/max_price, not
    // the guest-facing price with booking-engine markup) — a rough band
    // for schema.org priceRange, checked 2026-08-29. Update if rates shift
    // materially.
    priceRange: "£165–£295",
    sleeps: 2,
    description:
      "A contemporary studio chalet perched on the clifftop, with panoramic views across the Moray Firth and a log burner for cosy evenings in.",
    tagline: "For Couples and Their Dog",
    longDescription: [
      "Designed for two and genuinely built with dogs in mind, each studio chalet is design-led, beautifully finished, and shaped entirely around the view. Scottish and Scandinavian furnishings bring warm textures and natural materials into every corner, with pieces sourced from small local makers. The log burner keeps evenings cosy, while the balcony binoculars are there for dolphins, the aurora, and everything in between.",
      "These are dog-friendly chalets in Aberdeenshire where your companion is every bit as welcome as you are.",
    ],
    features: [
      "Sleeps 2",
      "Dog-friendly throughout",
      "Kitchen with coffee machine, grill, stove, microwave, oven, refrigerator, toaster",
      "Luxury bathroom with power shower & Gordon Castle toiletries",
      "Clifftop sea views over the Moray Firth",
      "Private balcony with binoculars",
      "Log burner",
      "On-site EV charging",
      "Wheelchair accessible",
    ],
    comingSoon: false,
    location: { lat: 57.670563223386880, lng: -2.337134626983644 },
    image: { src: "/7907_Gamrie_High_158.jpg", width: 7871, height: 5249 },
    gallery: [
      { src: "/Muckle View/1.jpg", width: 1920, height: 1280 },
      { src: "/Muckle View/2.jpg", width: 1920, height: 1281 },
      { src: "/Muckle View/3.jpg", width: 1920, height: 1280 },
      { src: "/Muckle View/4.jpg", width: 1920, height: 1280 },
      { src: "/Muckle View/5.jpg", width: 1920, height: 1280 },
      { src: "/Muckle View/6.jpg", width: 1920, height: 1281 },
      { src: "/Muckle View/7.jpg", width: 1920, height: 1281 },
      { src: "/Muckle View/8.jpg", width: 1920, height: 1281 },
      { src: "/Muckle View/9.jpg", width: 1920, height: 1280 },
      { src: "/Muckle View/10.jpg", width: 1920, height: 1280 },
      { src: "/Muckle View/11.jpg", width: 1920, height: 1280 },
      { src: "/Muckle View/12.jpg", width: 1920, height: 1280 },
      { src: "/Muckle View/13.jpg", width: 1920, height: 1280 },
      { src: "/Muckle View/14.jpg", width: 1920, height: 1281 },
      { src: "/Muckle View/15.jpg", width: 1920, height: 1281 },
      { src: "/Muckle View/16.jpg", width: 1920, height: 1280 },
      { src: "/Muckle View/17.jpg", width: 1920, height: 1280 },
      { src: "/Muckle View/18.jpg", width: 1920, height: 1280 },
      { src: "/Muckle View/19.jpg", width: 1668, height: 2500 },
      { src: "/Muckle View/20.jpg", width: 1920, height: 1281 },
      { src: "/Muckle View/21.jpg", width: 1667, height: 2500 },
      { src: "/Muckle View/22.jpg", width: 1920, height: 1281 },
      { src: "/Muckle View/23.jpg", width: 1920, height: 1280 },
      { src: "/Muckle View/24.jpg", width: 1920, height: 1280 },
      { src: "/Muckle View/25.jpg", width: 1920, height: 1281 },
      { src: "/Muckle View/26.jpg", width: 1920, height: 1280 },
      { src: "/Muckle View/27.jpg", width: 1920, height: 1280 },
      { src: "/Muckle View/28.jpg", width: 1920, height: 1281 },
      { src: "/Muckle View/29.jpg", width: 1920, height: 1280 },
      { src: "/Muckle View/30.jpg", width: 1920, height: 1281 },
      { src: "/Muckle View/31.jpg", width: 1920, height: 1280 },
      { src: "/Muckle View/32.jpg", width: 1920, height: 1281 },
      { src: "/Muckle View/33.jpg", width: 1920, height: 1281 },
      { src: "/Muckle View/34.jpg", width: 1668, height: 2500 },
      { src: "/Muckle View/35.jpg", width: 1920, height: 1281 },
      { src: "/Muckle View/36.jpg", width: 1920, height: 1280 },
      { src: "/Muckle View/37.jpg", width: 1667, height: 2500 },
      { src: "/Muckle View/38.jpg", width: 1920, height: 1281 },
      { src: "/Muckle View/39.jpg", width: 1668, height: 2500 },
      { src: "/Muckle View/40.jpg", width: 1920, height: 1280 },
      { src: "/Muckle View/41.jpg", width: 1920, height: 1281 },
      { src: "/Muckle View/42.jpg", width: 1920, height: 1281 },
      { src: "/Muckle View/43.jpg", width: 1920, height: 1280 },
    ],
  },
  {
    slug: "murray-cottage",
    name: "Murray Cottage",
    lodgifyRentalId: "794951",
    priceRange: "£104–£262",
    sleeps: 6,
    description:
      "The family home above Gardenstown, with three bedrooms, sweeping views of the Moray Firth, and room for everyone to settle in.",
    tagline: "Space for Everyone",
    longDescription: [
      "More generous in scale, the family home gives you room to spread out and truly settle in without losing an ounce of the stunning setting. The same considered design runs throughout: quality furnishings, local touches, and that sweeping view of the Firth framed in every window. It's the kind of place where children remember the holiday for years, and parents finally, properly rest.",
    ],
    features: [
      "Ideal for families and larger groups – 3 bedrooms (4 beds) – Sleeps 6",
      "Sea views over the Moray Firth",
      "Log burner",
      "Kitchen with coffee machine, dishwasher, stove, microwave, oven, refrigerator, toaster, vacuum cleaner",
      "Luxury bathroom with power shower",
      "Wi-fi",
    ],
    comingSoon: false,
    location: { lat: 57.671059600000000, lng: -2.333991600000000 },
    image: { src: "/78491_Murray-002.jpg", width: 4999, height: 3333 },
    gallery: [
      { src: "/Murray Cottage/1.jpg", width: 1920, height: 1280 },
      { src: "/Murray Cottage/2.jpg", width: 1920, height: 1280 },
      { src: "/Murray Cottage/3.jpg", width: 1920, height: 1280 },
      { src: "/Murray Cottage/4.jpg", width: 1920, height: 1280 },
      { src: "/Murray Cottage/5.jpg", width: 1920, height: 1280 },
      { src: "/Murray Cottage/6.jpg", width: 1920, height: 1280 },
      { src: "/Murray Cottage/7.jpg", width: 1920, height: 1280 },
      { src: "/Murray Cottage/8.jpg", width: 1920, height: 1280 },
      { src: "/Murray Cottage/9.jpg", width: 1920, height: 1280 },
      { src: "/Murray Cottage/10.jpg", width: 1920, height: 1280 },
      { src: "/Murray Cottage/11.jpg", width: 1920, height: 1280 },
      { src: "/Murray Cottage/12.jpg", width: 1920, height: 2880 },
      { src: "/Murray Cottage/13.jpg", width: 1920, height: 1280 },
      { src: "/Murray Cottage/14.jpg", width: 1920, height: 1280 },
      { src: "/Murray Cottage/15.jpg", width: 1920, height: 2880 },
      { src: "/Murray Cottage/16.jpg", width: 1920, height: 1280 },
      { src: "/Murray Cottage/17.jpg", width: 1920, height: 1284 },
      { src: "/Murray Cottage/18.jpg", width: 1920, height: 2884 },
      { src: "/Murray Cottage/19.jpg", width: 1920, height: 1280 },
      { src: "/Murray Cottage/20.jpg", width: 1920, height: 1280 },
      { src: "/Murray Cottage/21.jpg", width: 1920, height: 1280 },
      { src: "/Murray Cottage/22.jpg", width: 1920, height: 1280 },
      { src: "/Murray Cottage/23.jpg", width: 1920, height: 1280 },
      { src: "/Murray Cottage/24.jpg", width: 1920, height: 1280 },
      { src: "/Murray Cottage/25.jpg", width: 1920, height: 1280 },
      { src: "/Murray Cottage/26.jpg", width: 1920, height: 1280 },
      { src: "/Murray Cottage/27.jpg", width: 1920, height: 1280 },
      { src: "/Murray Cottage/28.jpg", width: 1920, height: 1280 },
      { src: "/Murray Cottage/29.jpg", width: 1920, height: 1280 },
      { src: "/Murray Cottage/30.jpg", width: 1920, height: 1280 },
      { src: "/Murray Cottage/31.jpg", width: 1920, height: 1280 },
      { src: "/Murray Cottage/32.jpg", width: 1920, height: 1280 },
      { src: "/Murray Cottage/33.jpg", width: 1920, height: 1280 },
      { src: "/Murray Cottage/34.jpg", width: 1920, height: 1280 },
    ],
  },
  {
    slug: "mohr-rest",
    name: "Mohr Rest",
    sleeps: 2,
    description:
      "A new chalet joining Gamrie Chalets, currently being prepared. Details and availability coming soon.",
    tagline: "For Couples and Their Dog",
    longDescription: [
      "Designed for two and genuinely built with dogs in mind, each studio chalet is design-led, beautifully finished, and shaped entirely around the view. Scottish and Scandinavian furnishings bring warm textures and natural materials into every corner, with pieces sourced from small local makers. The log burner keeps evenings cosy, while the balcony binoculars are there for dolphins, the aurora, and everything in between.",
      "These are dog-friendly chalets in Aberdeenshire where your companion is every bit as welcome as you are.",
    ],
    features: [
      "Sleeps 2",
      "Dog-friendly throughout",
      "Kitchen with coffee machine, grill, stove, microwave, oven, refrigerator, toaster",
      "Luxury bathroom with power shower & Gordon Castle toiletries",
      "Clifftop sea views over the Moray Firth",
      "Private balcony with binoculars",
      "Log burner",
      "On-site EV charging",
      "Wheelchair accessible",
    ],
    comingSoon: true,
    location: { lat: 57.670563223386880, lng: -2.337134626983644 },
    image: { src: "/Mohr Rest - Coming Soon.jpeg", width: 1920, height: 1440 },
  },
];

export const bookableProperties = properties.filter((p) => !p.comingSoon);
